'use strict';
var insert = require('../app/content/get_items_popularity');
// tests for get_items_popularity
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let chai = require('chai');
let should = chai.should();

describe('get_items_popularity', () => {
  before((done) => {
    done();
  });

  it('should succeed in getting items', (done) => {
    
    let event = {
      "body": "{\"category\": \"book\", \"subject\": \"physics\", \"price\": [\"1\", \"10000\"]}",
      "requestContext": {
        "identity": {
          "cognitoIdentityId": "USER-SUB-1235"
        }
      }
    };
    let context = {};
    let callback = (ctx, res) => {
      console.log(res);
      expect(res).to.not.be.empty;
      res.should.have.status(200);
      res.body.should.not.be.empty;
    };
  });
});
